// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:messageyrself/features/chat/models/message.dart';
import 'package:messageyrself/features/chat/models/session.dart';
import 'package:messageyrself/features/notebooks/models/notebook.dart';
import 'package:messageyrself/features/settings/models/app_settings.dart';
import 'package:messageyrself/features/settings/models/user_preset.dart';
import 'package:messageyrself/features/tags/models/tag.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(NotebookAdapter());
    registerAdapter(SessionAdapter());
    registerAdapter(TagAdapter());
    registerAdapter(UserPresetAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(NotebookAdapter());
    registerAdapter(SessionAdapter());
    registerAdapter(TagAdapter());
    registerAdapter(UserPresetAdapter());
  }
}
